### ISSUE TITLE
Gene search leads to wrong gene

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#1126]
Feedback from user:

> ...over 50% of the time I type in a gene name into the gnomAD browser, I end up on the wrong gene. I have to be incredibly careful about pausing as I type and deliberately choosing the right gene that comes up in the search-ahead function or most of the time I will land on the wrong gene. I realize this is partly user error (I assume I am somehow hitting return before I've quite finished typing the full name), but I've never understood why it is more likely to lead me astray than land on the right gene. But here is an example that may give some insight into the challenge. I was typing ABCD1 into the browser and accidentally landed on CX3CL1. I tried to recapitulate how I got there instead of ABCD1, and could see that typing in ABCD leads to CX3CL1 as the first option, not ABCD1. I assume this is because ABCD-3 is an alias of CX3CL1, but I wonder if we should remove the use of aliases in the type-ahead function and either not allow aliases, or only allow them if they fully map to the gene. So for example, only typing in the full ABCD-3 would get you to CX3CL1, not ABCD.

**Comment by phildarnowsky-broad** [comment]
One alternative is that we could keep the aliases, but sort things in the search-ahead dropdown so that the "real" gene always appears first. 

Perhaps as a complement to that we could add, for each search-ahead entry, a brief explanation of why that entry matches the search term. For instance, in this case, the option that was clicked in error might read "CX3CL1 (alias: ABCD-3)". But since that requires the user to read and interpret, rather than just knowing that they can count on a click in a certain spot to link to the gene itself, this approach probably wouldn't suffice by itself.

**Comment by mattsolo1** [comment]
I like the idea of adding the alias info to the search results

**Comment by mattsolo1** [comment]
@phildarnowsky-broad is this something we can QC using our test suite?

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 unless there's something odd about the components in question, should be.

**Comment by mattsolo1** [comment]
Related: https://github.com/broadinstitute/gnomad-browser/issues/1057

**Comment by phildarnowsky-broad** [comment]
It looks like the best way to implement this entails a small extension to GBTK, so I'm going to put a pin in this issue, go write that small extension, and return to this issue once GBTK is updated.

**Comment by nawatts** [comment]
For what it's worth, this extra term query in the ES query for gene search was intended to prioritize genes where the search term matched the primary symbol by increasing that gene's score.
https://github.com/broadinstitute/gnomad-browser/blob/65e4099bfcea184512eb620a44cf489f65d20c17/graphql-api/src/queries/gene-queries.ts#L128
