### ISSUE TITLE
Pangolin scores are showing as negative values

### ISSUE THREAD

**Issue by gm-bee** [broadinstitute/gnomad-browser#1249]
I'm exploring the new v4 data. I'm interested in the Pangolin scores. I notice the values are negative, when they should range from 0-1. 
Please see this ticket for a similar SpliceAI Lookup issue: https://github.com/broadinstitute/SpliceAI-lookup/issues/54

example:
https://gnomad.broadinstitute.org/variant/16-725232-C-T?dataset=gnomad_r4
https://spliceailookup.broadinstitute.org/#variant=chr16-725232-C-T&hg=38&distance=50&mask=1&ra=0

**Comment by KoalaQin** [comment]
@gm-bee Thanks for your interest in Pangolin scores. 
Unlike the SpliceAI Lookup Browser, we don't show if a variant is splice loss or splice gain, we use the negative and positive sign to differentiate them, because we took the largest delta score across 2 splicing consequences, which reflects the probability of the variant being splice-altering. If a variant is predicted to fall within multiple genes, score is across all relevant genes. Note that there is different behavior from spliceAI: splice gain is noted as the increase in splice usage (scores range from 0 to 1) and splice loss as the decrease in splice usage (scores range from 0 to -1). The Pangolin authors proposed a cutoff of >|0.2| for the predicted increase or decrease in splice site usage. You can find the description on our help page: https://gnomad.broadinstitute.org/help/v4-hts
If you need to see how it was processed, it's here as in code: https://github.com/broadinstitute/gnomad_qc/blob/cfa7e694b15f3a774c34665fa13fdde4c2d551da/gnomad_qc/v4/annotations/insilico_predictors.py#L233
Let me know if you have further questions.

**Comment by rileyhgrant** [comment]
Closed as answered by @KoalaQin
