### ISSUE TITLE
Expose the non_ukb v4 short variant subset

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#1448]
@sambaxter suggested non_ukb subset should be available in the browser for v4 exome variants. 

I believe the frequencies are already in Elasticsearch.

https://github.com/broadinstitute/gnomad-browser/blob/560a828e49d1a489d0ca993441d29f20fa5459ef/data-pipeline/schemas/gnomad_v4_variants/annotate_gnomad_v4_variants/output/gnomad_v4_variants_annotated_1.ht.schema#L30

Therefore it should be easy to add this in the same way we typically expose subsets, and we don't need to load additional data.

**Comment by ch-kr** [comment]
As discussed in this morning's standup: the non-UKB subset only impacts the exomes within gnomAD v4. Another subset in v2 that impacts only one data type is the non-cancer subset; this subset also only impacts the exomes in v2, because all v2 genomes are non-cancer.

Here's an example variant: https://gnomad.broadinstitute.org/variant/1-55505679-G-A?dataset=gnomad_r2_1
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/5187eeff-88a5-4715-835a-618187e604ac)
and [non-cancer](https://gnomad.broadinstitute.org/variant/1-55505679-G-A?dataset=gnomad_r2_1_non_cancer):
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/9d20e75e-2968-453b-b8cb-7e57c0aef8a0)

Commenting here in case looking at the behavior of the v2 non-cancer subset is helpful when implementing the non-UKB v4 subset

**Comment by rileyhgrant** [comment]
Closed by #1490
