### ISSUE TITLE
Download of Joint Frequency file does not work

### ISSUE THREAD

**Issue by lush-ldw** [broadinstitute/gnomad-browser#1519]
I tried to download the Joint sites Hail Table from the download page, but all the links seem to be dead.

This is the error message get from attempting to download the file using the Google-link:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: gcp-public-data--gnomad/release/4.1/ht/joint/gnomad.joint.v4.1.site.ht
</Details>
</Error>

The Amazon/Microsoft links show similar errors.

**Comment by sjahl** [comment]
Thanks for the report @lush-ldw -- This was a typo that was fixed in https://github.com/broadinstitute/gnomad-browser/pull/1513 , and it should be getting deployed shortly.

In the mean time, you can pull down the joint frequency table by making sure your request path is looking for gnomad.joint.v4.1.**sites**.ht rather than gnomad.joint.v4.1.**site**.ht.

`gsutil cp -r gs://gcp-public-data--gnomad/release/4.1/ht/joint/gnomad.joint.v4.1.sites.ht .`
