### ISSUE TITLE
7-21706736-G-A Variant in DNAH11 not showing up in gnomAD Variant table 

### ISSUE THREAD

**Issue by kathrynrussell** [broadinstitute/gnomad-browser#1622]
### What you did:

https://gnomad.broadinstitute.org/gene/ENSG00000105877?dataset=gnomad_r4 

I went to the above link to look for a variant in DNAH11. The variant is c.6547-963G>A (gnomAD ID: 7-21706736-G-A, ClinVar ID:  3068449, Allele Registry ID: CA155078618). I searched for this variant in the variant table using both the c. nomenclature and the gnomAD ID.  This is a genomes only variant. 

### What you expected to see after you did that:

I would have expected to see the variant in the variant table because it has a gnomAD ID and I am in the correct gene. 

### What you actually saw after you did that:

The variant was not in the variant table. However, if you search the variant ID in the top search bar (the one in the black banner at the top of the gnomAD page), it does bring you to the correct variant page. 

![Screenshot 2024-09-05 at 1 54 27 PM](https://github.com/user-attachments/assets/6257c07b-cd35-4cba-9e6e-5cfe424141b0)
![Screenshot 2024-09-05 at 1 54 57 PM](https://github.com/user-attachments/assets/75e37b18-393e-4b3d-9926-978fec6f8975)
![Screenshot 2024-09-05 at 1 55 17 PM](https://github.com/user-attachments/assets/1bec85bb-2338-4d25-960b-e6b0af4db53a)

**Comment by rileyhgrant** [comment]
Hey @kathrynrussell,

This is due to gnomAD's gene page only displaying variants in, or very close to, exons (it displays variants in the CDS regions +- 75 bps). 

This particular variant appears to be very far from its neighboring exons (https://gnomad.broadinstitute.org/region/7-21704681-21708791?dataset=gnomad_r4&variant=7-21706736-G-A), and as such its not showing up on the gene page, but does show up in a region, or variant page.

Definitely let me know if I'm misunderstanding something, and thanks for filing this issue!

**Comment by kathrynrussell** [comment]
Hi Riley,

Thanks for clarifying, I didn't realize that the deep intronic variants
didn't show up on the table when looking at the whole gene, but in
hindsight it makes a lot of sense!

Best,
Katie

**Comment by rileyhgrant** [comment]
Glad to help clarify, thanks again for submitting this. 

Going to close this issue.
