### ISSUE TITLE
Add colors for new analyst annotations (e.g., CADD, REVEL, PrimateAI, SpliceAI)

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#626]
See conversation here: https://atgu.slack.com/archives/CNLMF0JLV/p1603726961208800?thread_ts=1603724880.205800&cid=CNLMF0JLV

**Comment by nawatts** [comment]
@hanars does seqr have color scales defined for these values?

**Comment by hanars** [comment]
Yes, if the value is above dangerThreshold its red, otherwise above warningThreshold its yellow, and otherwise its green. 

https://github.com/broadinstitute/seqr/blob/master/ui/shared/components/panel/variants/Predictions.jsx#L68

We also have per-gene values for primate AI that we use when available. If we have those, we do red if its above the 75th percentile for that gene, and yellow if its over the 25th, and otherwise green

Heres the script that we use to get those values: https://github.com/broadinstitute/seqr/blob/master/reference_data/management/commands/update_primate_ai.py

**Comment by nawatts** [comment]
Thanks @hanars.
