### ISSUE TITLE
Create visualizations with only my data

### ISSUE THREAD

**Issue by GenomicsPrograms** [broadinstitute/gnomad-browser#665]
Updated Comment - I have my own raw WES 444GB VCF, and VEP annotated version of this VCF.

I want to generate the coverage plot and the other plots in gnomAD, using only my data (or specific columns from them). Do you have any recommendations?

**Comment by nawatts** [comment]
Components for many of the visualizations in the gnomAD browser are [available on NPM](https://www.npmjs.com/org/gnomad). Unfortunately, most of them are currently poorly documented, but the code can be found in [broadinstitute/gnomad-browser-toolkit](https://github.com/broadinstitute/gnomad-browser-toolkit).

For manipulating data into the format expected by visualization components, we mostly use [Hail](https://hail.is/). Since your data is in VCF format, [bcftools](http://samtools.github.io/bcftools/bcftools.html) may also be useful for extracting columns.

**Comment by GenomicsPrograms** [comment]
How do I run the pipelines with my VCF? Is there one python script, that calls all other pipelines?

**Comment by nawatts** [comment]
The pipelines for the browser are all tailored to the gnomAD Hail Tables and their format. They likely will not work if run unmodified on another dataset. The code in [data-pipeline/src/data_pipeline/datasets](https://github.com/broadinstitute/gnomad-browser/tree/7818b76dadc2a5419bc89593080643d90b29e294/data-pipeline/src/data_pipeline/datasets) may be useful as a reference. The pipelines for [ExAC variants](https://github.com/broadinstitute/gnomad-browser/blob/7818b76dadc2a5419bc89593080643d90b29e294/data-pipeline/src/data_pipeline/datasets/exac/exac_variants.py) and [ClinVar variants](https://github.com/broadinstitute/gnomad-browser/blob/7818b76dadc2a5419bc89593080643d90b29e294/data-pipeline/src/data_pipeline/datasets/clinvar.py) import data from VCFs.
