### ISSUE TITLE
Monitoring for API response times

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#706]
Based on logs from #705

**Comment by nawatts** [comment]
Log based distribution metrics seem like the way to go about this.

https://cloud.google.com/logging/docs/logs-based-metrics#distribution_metrics

**Comment by sjahl** [comment]
Note that we get backend response times from the load balancer metrics, and have mostly been using percentile latencies from this to measure/understand performance.

I think the underlying ask here is to provide more specific latency metrics from the graphql resolvers to better understand performance within the app, which is probably still worth doing.

But, I'm going to close this as done, since the latency from the perspective of the load balancer seems to get the job done as far as I'm concerned. The ratio of 502s to successful requests seems to be one of the more actionable metrics as well, which we're monitoring and alerting on via https://console.cloud.google.com/monitoring/alerting/policies/12568548432416248771?organizationId=43663619702&project=exac-gnomad
