### ISSUE TITLE
Upgrade to Elasticsearch 7.17+ and ECK operator

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#929]
See: https://github.com/broadinstitute/gnomad-browser/issues/928

**Comment by peternixon** [comment]
The below patch allows deployment with the current code base:
diff --git a/deploy/deployctl/subcommands/setup.py b/deploy/deployctl/subcommands/setup.py
index 219a25a8..94a501b7 100644
--- a/deploy/deployctl/subcommands/setup.py
+++ b/deploy/deployctl/subcommands/setup.py
@@ -210,7 +210,7 @@ def create_cluster() -> None:
             f"--zone={config.zone}",
             "--release-channel=stable",
             "--enable-autorepair",
-            "--enable-autoupgrade",
+            "--cluster-version=1.21.14-gke.3000",
             "--maintenance-window=7:00",
             f"--service-account={config.gke_service_account_full_name}",
             f"--network={config.network_name}",

**Comment by sjahl** [comment]
Just following some threads on what our elasticsearch export looks like, It kinda seems like we may be limited to Elasticsearch 7 on the Hail end of things: https://github.com/hail-is/hail/blob/b124e86925221bc1c82662ff429e4ab480c4b080/hail/python/hail/methods/impex.py#L2950

I see some discussion in the Hail zulip that indicates at least one person has managed to compile hail with ES 8 support. On one hand, I don't like the idea of doing any trailblazing here, but on the other, Elastic is EOL-ing ES 7 in August 2023. So, I think it makes sense to upgrade to 7 since we have to do that anyway to make it to 8, and then on the longer term we can start trying to work out ES 8 support status in Hail.

**Comment by sjahl** [comment]
ES7 Compatibility (both in the k8s manifests and API service) was shipped in https://github.com/broadinstitute/gnomad-browser/commit/65e4099bfcea184512eb620a44cf489f65d20c17
