### ISSUE TITLE
Create testing suite

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#930]
Currently, it is difficult to carry out large refactoring efforts while being confident that no external-facing behavior has broken.

@phildarnowsky-broad proposed a snapshot-based approach for ensuring exact HTML/source is generated. Also includes an approach to mocking calls to API/graphql.

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 per your suggestion in Slack, I like the idea of spinning off a separate PR from my big in-progress refactoring, with just the infrastructure to support tests plus one or two of the simpler snapshot-based tests I've added as examples. That way you and @rileyhgrant would be able to take advantage of that right away without having to wait for me to finish the bigger-scope refactoring.

I'd also like to propose that, going forward, we consider lack of appropriate testing in a PR to be a blocker. This doesn't mean that we have to immediately write tests to cover the entire codebase, but rather more like what I'm doing with the big refactoring, covering only what you change or might otherwise break and going for breadth over depth. This plays again to the strengths of snapshot testing, and as you'll see those are very easy to add. We should talk soon about a more comprehensive testing strategy, but the snapshots are low-hanging fruit and pretty juicy fruit at that.

**Comment by mattsolo1** [comment]
Sounds good to me 👍

Another question: will you be adding to these tests to CI/Github actions?

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 the new tests should fall under the existing "Browser CI" action, though I haven't actually checked if that works yet. I'll confirm it does before we call this one done.

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 at least, the one I'm going to merge in as part of this PR should run under the browser test, but then in the refactoring PR, I do introduce a new subdirectory that I had to explicitly add to the test config to get tests there to run, so probably I'll have to do something similar on the CI side. I may look for a way to refactor actions then so that we don't have to remember to do these things manually.

**Comment by phildarnowsky-broad** [comment]
> @mattsolo1 the new tests should fall under the existing "Browser CI" action

...and indeed they do.
